language: rust
sudo: false

rust:
  - nightly
  - stable

matrix:
  allow_failures:
    - rust: nightly

env:
  - TEST_DIR=simplemad
  - TEST_DIR=simplemad_sys

script: cd $TEST_DIR && cargo build && cargo test

