language: rust
sudo: false

rust:
  - nightly
  - stable

matrix:
  allow_failures:
    - rust: nightly

before_install:
    - sudo apt -y install libmad0 libmad0-dev

env:
  - TEST_DIR=simplemad
  - TEST_DIR=simplemad_sys

script: cd $TEST_DIR && cargo build && cargo test

